development:
  adapter: postgresql
  encoding: unicode
  database: brews_development

test:
  adapter: postgresql
  encoding: unicode
  database: brews_test

production:
  adapter: postgresql
  user: brews
  encoding: unicode
  database: brews_production
